### ISSUE TITLE
When click on TakePicture button

### ISSUE THREAD

**Issue by Hitexroid** [sangmingming/android-instagram-filter#4]
> E/AndroidRuntime: FATAL EXCEPTION: main
>                   Process: jey.photo.hitexroid.photojey, PID: 29742
>                   java.lang.RuntimeException: setParameters failed
>                       at android.hardware.Camera.native_setParameters(Native Method)
>                       at android.hardware.Camera.setParameters(Camera.java:1939)
>                       at jp.co.cyberagent.android.gpuimage.sample.activity.ActivityCamera.takePicture(ActivityCamera.java:150)
>                       at jp.co.cyberagent.android.gpuimage.sample.activity.ActivityCamera.onClick(ActivityCamera.java:126)
>                       at android.view.View.performClick(View.java:5280)
>                       at android.view.View$PerformClick.run(View.java:21239)
>                       at android.os.Handler.handleCallback(Handler.java:739)
>                       at android.os.Handler.dispatchMessage(Handler.java:95)

**Comment by sangmingming** [comment]
this is a camera error， not a error of gupimage.
